# Generated by Django 5.1.4 on 2024-12-07 14:52

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Número do telefone', max_length=31)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
