# Generated by Django 5.1.4 on 2024-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_agenda_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
